import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Sidebar from '@/components/Sidebar'
import Feed from "../components/Feed"
import Widgets from '@/components/Widgets'

const inter = Inter({ subsets: ['latin'] })

export default function Home({newsResult, randomUserResults}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex min-h-screen   mx-auto'>

      {/* sidebar  */}
      <Sidebar/>

      {/* Feed  */}

      <Feed/>

      {/* Widgets  */}

      <Widgets newsResult ={newsResult} randomUserResults = {randomUserResults}/>


      </main>
      

      



    </>
  )
}


export async function getServerSideProps(){
  const newsResult = await fetch("https://saurav.tech/NewsAPI/top-headlines/category/business/us.json" )
                      .then((res) => res.json())

const randomUserResults = await fetch("https://randomuser.me/api/?results=30&inc=name,login,picture")
                      .then((res) => res.json())

                      return {
                        props: {
                          newsResult,
                          randomUserResults
                        },
                      }
}
